export const MEMORY_CONFIG = {
  book: {
    id: 'book',
    label: 'Book',
    position: [-1.8, -0.82, -0.4],
    cameraTarget: [-1.8, -0.68, 0.25],
    title: "Six Weeks I Didn't Write Down",
    color: '#7a4a2e',
    particleColor: '#e0a3a3',
    // ambientTrack: placeholder for the song,
  },
  letter: {
    id: 'letter',
    label: 'Letter',
    position: [-0.1, -0.82, 0.3],
    cameraTarget: [-0.6, -0.62, 0.75],
    title: 'Unsent',
    color: '#f4ecd8',
    particleColor: '#6fbf73',
  },
  record: {
    id: 'record',
    label: 'Record',
    position: [1.5, -0.7, 0.5],
    cameraTarget: [0.6, -0.55, -0.1],
    title: 'Track 4, Every Sunday',
    color: '#c9a86a',
    particleColor: '#4a90d9',
  },
  picture: {
    id: 'picture',
    label: 'Picture',
    position: [-0.6, -0.3, -1.1],
    cameraTarget: [-0.6, 0.2, 2.5],
    title: 'The One Where No One Is Looking at the Camera',
    color: '#2b2b2b',
    particleColor: '#87ceeb',
  },
}